### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by CarlSargunar** [mattbegent/Umbraco.Community.SkrivLet#12]
Looks really cool! Any plans to add documentation to this in the repo? I have questions like

- What format are you using to store the content in the back end?
- Is the property directly swappable with existing rich text editors for existing sites?
- Other questions as they occur to me

Good work! Looks fantastic!

**Comment by CarlSargunar** [comment]
I was just being lazy and not trying it myself. Looks cool :-)

**Comment by stevetemple** [comment]
Ha ha, 

The format is JSON, it's bascially editorJS behind the scenes

It will not swap with RTE, maybe something we could consider making first load transform the data? Would be handy for some of our sites.

We haven't tried dropping it into Block List, Block Grid, Nested Content etc yet, should check to see how it performs inside other elements
